# Base de données pré-remplie de plantes courantes (jardin français)

SEED_PLANTS = [
    {
        "common_name": "Rosier",
        "scientific_name": "Rosa",
        "exposure": "Ensoleillé",
        "soil_type": "Riche, bien drainé",
        "plant_type": "Arbuste",
        "hardiness": "Zone 5-9 (-15°C)",
        "soil_humidity": "Frais",
        "foliage_type": "Caduc",
        "height_min": 0.5,
        "height_max": 2.0,
        "flowering_start": "05-15",
        "flowering_end": "10-15",
        "known_diseases": "Oïdium, marsonia, rouille, puceron",
        "pruning_start": "02-15",
        "pruning_end": "03-15",
        "pruning_advice": "Couper les tiges à 3-5 yeux au-dessus du sol, éliminer le bois mort",
        "fertilizing_start": "03-01",
        "fertilizing_end": "03-31",
        "fertilizing_quantity": "50g/m² au pied",
        "fertilizing_type": "Engrais spécial rosiers (NPK riche en potasse)",
        "image_url": "",
        "source_api_id": "",
        "notes": "",
        "garden_location": "",
        "date_planted": ""
    },
    {
        "common_name": "Lavande",
        "scientific_name": "Lavandula angustifolia",
        "exposure": "Ensoleillé",
        "soil_type": "Sec, calcaire, drainant",
        "plant_type": "Arbuste",
        "hardiness": "Zone 5-9 (-15°C)",
        "soil_humidity": "Sec",
        "foliage_type": "Persistant",
        "height_min": 0.3,
        "height_max": 0.8,
        "flowering_start": "06-15",
        "flowering_end": "08-15",
        "known_diseases": "Cicadelle, cercosporiose",
        "pruning_start": "09-01",
        "pruning_end": "09-30",
        "pruning_advice": "Tailler en boule après floraison, ne pas couper dans le bois",
        "fertilizing_start": "03-01",
        "fertilizing_end": "03-31",
        "fertilizing_quantity": "Peu, sol pauvre préféré",
        "fertilizing_type": "Compost léger ou aucun engrais",
        "image_url": "",
        "source_api_id": "",
        "notes": "",
        "garden_location": "",
        "date_planted": ""
    },
    {
        "common_name": "Pommier",
        "scientific_name": "Malus domestica",
        "exposure": "Ensoleillé",
        "soil_type": "Riche, drainant",
        "plant_type": "Fruitier",
        "hardiness": "Zone 4-8 (-25°C)",
        "soil_humidity": "Frais",
        "foliage_type": "Caduc",
        "height_min": 2.0,
        "height_max": 8.0,
        "flowering_start": "04-01",
        "flowering_end": "05-01",
        "known_diseases": "Tavelure, oïdium, carpocapse, puceron lanigère",
        "pruning_start": "12-01",
        "pruning_end": "02-28",
        "pruning_advice": "Taille de formation en hiver hors gel, aérer le centre de l'arbre",
        "fertilizing_start": "02-15",
        "fertilizing_end": "03-15",
        "fertilizing_quantity": "2-3 kg de compost mûr au pied",
        "fertilizing_type": "Compost organique ou engrais fruitier NPK",
        "image_url": "",
        "source_api_id": "",
        "notes": "",
        "garden_location": "",
        "date_planted": ""
    },
    {
        "common_name": "Hortensia",
        "scientific_name": "Hydrangea macrophylla",
        "exposure": "Mi-ombre",
        "soil_type": "Riche, humifère, acide",
        "plant_type": "Arbuste",
        "hardiness": "Zone 6-9 (-10°C)",
        "soil_humidity": "Humide",
        "foliage_type": "Caduc",
        "height_min": 1.0,
        "height_max": 2.0,
        "flowering_start": "06-01",
        "flowering_end": "09-30",
        "known_diseases": "Oïdium, chlorose, cochenille",
        "pruning_start": "03-01",
        "pruning_end": "03-31",
        "pruning_advice": "Couper les fleurs fanées au-dessus des deux premiers bourgeons",
        "fertilizing_start": "04-01",
        "fertilizing_end": "04-30",
        "fertilizing_quantity": "100g/m²",
        "fertilizing_type": "Engrais plantes de terre de bruyère",
        "image_url": "",
        "source_api_id": "",
        "notes": "",
        "garden_location": "",
        "date_planted": ""
    },
    {
        "common_name": "Tomate",
        "scientific_name": "Solanum lycopersicum",
        "exposure": "Ensoleillé",
        "soil_type": "Riche, bien drainé",
        "plant_type": "Potager",
        "hardiness": "Annuelle (sensible au gel)",
        "soil_humidity": "Frais",
        "foliage_type": "Caduc",
        "height_min": 0.5,
        "height_max": 2.0,
        "flowering_start": "06-01",
        "flowering_end": "09-01",
        "known_diseases": "Mildiou, oïdium, alternariose",
        "pruning_start": "06-01",
        "pruning_end": "08-31",
        "pruning_advice": "Supprimer les gourmands chaque semaine, effeuiller le bas",
        "fertilizing_start": "05-01",
        "fertilizing_end": "08-31",
        "fertilizing_quantity": "Toutes les 2 semaines, dose selon produit",
        "fertilizing_type": "Engrais tomate riche en potasse",
        "image_url": "",
        "source_api_id": "",
        "notes": "",
        "garden_location": "",
        "date_planted": ""
    },
    {
        "common_name": "Olivier",
        "scientific_name": "Olea europaea",
        "exposure": "Ensoleillé",
        "soil_type": "Drainant, calcaire",
        "plant_type": "Arbre",
        "hardiness": "Zone 8-10 (-10°C)",
        "soil_humidity": "Sec",
        "foliage_type": "Persistant",
        "height_min": 2.0,
        "height_max": 10.0,
        "flowering_start": "05-01",
        "flowering_end": "06-15",
        "known_diseases": "Œil de paon, cochenille noire, mouche de l'olive",
        "pruning_start": "04-01",
        "pruning_end": "05-31",
        "pruning_advice": "Tailler après les gelées, aérer le centre, forme en vase",
        "fertilizing_start": "03-01",
        "fertilizing_end": "03-31",
        "fertilizing_quantity": "500g/m² au pied",
        "fertilizing_type": "Engrais organique riche en azote",
        "image_url": "",
        "source_api_id": "",
        "notes": "",
        "garden_location": "",
        "date_planted": ""
    },
    {
        "common_name": "Camélia",
        "scientific_name": "Camellia japonica",
        "exposure": "Mi-ombre",
        "soil_type": "Acide, humifère",
        "plant_type": "Arbuste",
        "hardiness": "Zone 7-9 (-12°C)",
        "soil_humidity": "Frais",
        "foliage_type": "Persistant",
        "height_min": 1.5,
        "height_max": 4.0,
        "flowering_start": "01-15",
        "flowering_end": "03-31",
        "known_diseases": "Cochenille, fumagine, pourriture des racines",
        "pruning_start": "04-01",
        "pruning_end": "04-30",
        "pruning_advice": "Tailler juste après floraison, légère taille de forme",
        "fertilizing_start": "04-01",
        "fertilizing_end": "04-30",
        "fertilizing_quantity": "80g/m²",
        "fertilizing_type": "Engrais plantes de terre de bruyère",
        "image_url": "",
        "source_api_id": "",
        "notes": "",
        "garden_location": "",
        "date_planted": ""
    },
    {
        "common_name": "Laurier-rose",
        "scientific_name": "Nerium oleander",
        "exposure": "Ensoleillé",
        "soil_type": "Drainant",
        "plant_type": "Arbuste",
        "hardiness": "Zone 8-10 (-5°C)",
        "soil_humidity": "Sec à frais",
        "foliage_type": "Persistant",
        "height_min": 1.5,
        "height_max": 3.0,
        "flowering_start": "06-01",
        "flowering_end": "09-30",
        "known_diseases": "Cochenille, gale du laurier-rose",
        "pruning_start": "09-15",
        "pruning_end": "10-15",
        "pruning_advice": "Tailler après floraison, raccourcir les tiges d'un tiers",
        "fertilizing_start": "04-01",
        "fertilizing_end": "08-31",
        "fertilizing_quantity": "Toutes les 3 semaines",
        "fertilizing_type": "Engrais plantes fleuries liquide",
        "image_url": "",
        "source_api_id": "",
        "notes": "",
        "garden_location": "",
        "date_planted": ""
    }
]